/**
 * Dispatch domain — worker registry data access.
 *
 * Uses raw SQL via the `pg` singleton pool (same externalization pattern as
 * apps/web/lib/db.ts). No ORM. Parameterized queries only ($1, $2…).
 * All IDs are UUID generated by Postgres gen_random_uuid().
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _pool: any = null;

function getPool(): {
  query: (sql: string, params?: unknown[]) => Promise<{ rows: unknown[] }>;
} {
  if (_pool) return _pool;
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { Pool: PgPool } = require("pg") as {
    Pool: new (config: Record<string, unknown>) => {
      query: (sql: string, params?: unknown[]) => Promise<{ rows: unknown[] }>;
    };
  };
  _pool = new PgPool({
    connectionString: process.env.DATABASE_URL,
    max: 10,
    idleTimeoutMillis: 30_000,
  });
  return _pool;
}

export interface Worker {
  id: string;
  name: string;
  email: string;
  phone: string | null;
  trade: string;
  certifications: string[];
  availability: Record<string, string[]>;
  travel_zones: string[];
  reliability_score: number;
  status: "active" | "inactive";
  notes: string | null;
  created_at: Date;
  updated_at: Date;
}

export interface CreateWorkerInput {
  name: string;
  email: string;
  phone?: string;
  trade: string;
  certifications?: string[];
  availability?: Record<string, string[]>;
  travel_zones?: string[];
  reliability_score?: number;
  status?: "active" | "inactive";
  notes?: string;
}

async function ensureTable(): Promise<void> {
  const pool = getPool();
  await pool.query(`
    CREATE TABLE IF NOT EXISTS dispatch_workers (
      id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
      name          TEXT         NOT NULL,
      email         TEXT         NOT NULL UNIQUE,
      phone         TEXT,
      trade         TEXT         NOT NULL,
      certifications JSONB       NOT NULL DEFAULT '[]',
      availability  JSONB        NOT NULL DEFAULT '{}',
      travel_zones  JSONB        NOT NULL DEFAULT '[]',
      reliability_score NUMERIC(5,2) NOT NULL DEFAULT 100,
      status        TEXT         NOT NULL DEFAULT 'active',
      notes         TEXT,
      created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
      updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    )
  `);
}

function parseWorker(row: Record<string, unknown>): Worker {
  return {
    id: row.id as string,
    name: row.name as string,
    email: row.email as string,
    phone: (row.phone as string | null) ?? null,
    trade: row.trade as string,
    certifications: Array.isArray(row.certifications)
      ? (row.certifications as string[])
      : [],
    availability:
      typeof row.availability === "object" && row.availability !== null
        ? (row.availability as Record<string, string[]>)
        : {},
    travel_zones: Array.isArray(row.travel_zones)
      ? (row.travel_zones as string[])
      : [],
    reliability_score: Number(row.reliability_score),
    status: row.status as "active" | "inactive",
    notes: (row.notes as string | null) ?? null,
    created_at: row.created_at as Date,
    updated_at: row.updated_at as Date,
  };
}

export async function listWorkers(
  opts: { search?: string; status?: string } = {},
): Promise<Worker[]> {
  await ensureTable();
  const pool = getPool();
  const params: unknown[] = [];
  const conditions: string[] = [];

  if (opts.search) {
    params.push(`%${opts.search}%`);
    const idx = params.length;
    conditions.push(
      `(name ILIKE $${idx} OR email ILIKE $${idx} OR trade ILIKE $${idx})`,
    );
  }

  if (opts.status && (opts.status === "active" || opts.status === "inactive")) {
    params.push(opts.status);
    conditions.push(`status = $${params.length}`);
  }

  const where =
    conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";
  const result = await pool.query(
    `SELECT * FROM dispatch_workers ${where} ORDER BY name ASC`,
    params,
  );
  return (result.rows as Record<string, unknown>[]).map(parseWorker);
}

export async function getWorker(id: string): Promise<Worker | null> {
  await ensureTable();
  const pool = getPool();
  const result = await pool.query(
    "SELECT * FROM dispatch_workers WHERE id = $1",
    [id],
  );
  const rows = result.rows as Record<string, unknown>[];
  return rows[0] ? parseWorker(rows[0]) : null;
}

export async function createWorker(input: CreateWorkerInput): Promise<Worker> {
  await ensureTable();
  const pool = getPool();
  const result = await pool.query(
    `INSERT INTO dispatch_workers
       (name, email, phone, trade, certifications, availability, travel_zones, reliability_score, status, notes)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
     RETURNING *`,
    [
      input.name,
      input.email,
      input.phone ?? null,
      input.trade,
      JSON.stringify(input.certifications ?? []),
      JSON.stringify(input.availability ?? {}),
      JSON.stringify(input.travel_zones ?? []),
      input.reliability_score ?? 100,
      input.status ?? "active",
      input.notes ?? null,
    ],
  );
  const rows = result.rows as Record<string, unknown>[];
  return parseWorker(rows[0]);
}

export async function updateWorkerStatus(
  id: string,
  status: "active" | "inactive",
): Promise<void> {
  await ensureTable();
  const pool = getPool();
  await pool.query(
    "UPDATE dispatch_workers SET status = $1, updated_at = NOW() WHERE id = $2",
    [status, id],
  );
}
